[theme]
# Mode light par d√©faut
base="light"
primaryColor="#D92332"
backgroundColor="#FFFFFF"
secondaryBackgroundColor="#F8FAFC"
textColor="#1E293B"
font="sans serif"

[browser]
gatherUsageStats = false

[server]
headless = true
